name: Build Rubeus (.NET 3.5)

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    # 必须使用 windows-2019，因为它对旧版 .NET 框架支持更好
    runs-on: windows-2019 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore Rubeus.sln

    - name: Build Rubeus (Targeting .NET 3.5)
      # 这里通过参数强制指定框架版本为 v3.5
      run: msbuild Rubeus.sln /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion=v3.5

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v3
      with:
        name: Rubeus-v3.5-Binary
        path: |
          Rubeus/bin/Release/Rubeus.exe
