name: Build Rubeus

on: 
  workflow_dispatch: # 允许你手动点击按钮触发编译

jobs:
  build:
    runs-on: windows-2019 # 使用更稳定的旧版 Windows 环境以支持旧版 .NET

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore Rubeus.sln

    - name: Build Rubeus
      run: msbuild Rubeus.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v3
      with:
        name: Rubeus-Binary
        # 这里的路径必须匹配编译出的位置，Rubeus 默认通常在这里：
        path: |
          Rubeus/bin/Release/Rubeus.exe
